# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Terminal Weahter CI | Node.js

on:
  push:
    branches: [ master ]

jobs:
  # Install the Program
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    # Setup Node and Directory
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    # Setup API
    - name: Setup API Key
      run: |
        npm install -g pkg
        npm install
        ./setSecret.sh ${{ secrets.weather_api_key }}

    # Run Program
    - name: Run Program
      run: npm start

    # Build the Executable
    - name: Build Program
      run: npm run-script build

    # Test the Program
    - name: Test Program
      run: npm run-script test

  # Install the Program
  coverage:
    runs-on: ubuntu-latest
    name: Coverage Report
    steps:
    # Setup Node and Directory
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    # Setup For Coverage
    - name: Setup API Key
      run: |
        npm install -g pkg
        npm install
        ./setSecret.sh ${{ secrets.weather_api_key }}
        npm start
        touch .gitignore
        echo node_modules >> .gitignore
    # Get Coverage
    - name: Check Coverage
      uses: ArtiomTr/jest-coverage-report-action@v2
